language: java
jdk:
- openjdk8

addons:
    apt:
        packages:
            - ant 
    sonarcloud:
        organization: "simonesinceri"
        token:
            secure: "bb3f97210481d5fc7392d6312f08bffd64a359dd"
script:
    - ant build
    - sonar-scanner